
export  const MOCK_DATAS = [
    {
      id: 1,
      content: "Today is November 26th.",
      position: 1,
      timeStart: 3.7,
      timeEnd: 6,
    },
    {
      id: 2,
      content: "It snowed all day today.",
      position: 2,
      timeStart: 6.6,
      timeEnd: 8.6,
    },
    {
      id: 3,
      content: "The snow is beautiful.",
      position: 3,
      timeStart: 9.3,
      timeEnd: 11.2,
    },
    {
      id: 4,
      content: "The snow finally stopped.",
      position: 4,
      timeStart: 12,
      timeEnd: 14.5,
    },
    {
      id: 5,
      content: "My sister and I are excited.",
      position: 5,
      timeStart: 15.3,
      timeEnd: 17.3,
    },
    {
      id: 6,
      content: "My mom doesn't like the snow.",
      position: 6,
      timeStart: 18.1,
      timeEnd: 20.2,
    },
    {
      id: 7,
      content: "My mom has to shovel the driveway.",
      position: 7,
      timeStart: 21,
      timeEnd: 23.4,
    },
    {
      id: 8,
      content: "My sister and I get to play.",
      position: 8,
      timeStart: 24.2,
      timeEnd: 26.3,
    },
    {
      id: 9,
      content: "I put on my hat and mittens.",
      position: 9,
      timeStart: 27.3,
      timeEnd: 29.51,
    },
    {
      id: 10,
      content: "My mom puts on my scarf.",
      position: 10,
      timeStart: 30.1,
      timeEnd: 32.1,
    },
    {
      id: 11,
      content: "My mom zippers my jacket.",
      position: 11,
      timeStart: 32.8,
      timeEnd: 34.9,
    },
    {
      id: 12,
      content: "My sister puts on her hat and mittens.",
      position: 12,
      timeStart: 35.5,
      timeEnd: 38.4,
    },
    {
      id: 13,
      content: "My mom puts on her scarf.",
      position: 13,
      timeStart: 39.1,
      timeEnd: 41.3,
    },
    {
      id: 14,
      content: "My mom zippers her jacket.",
      position: 14,
      timeStart: 42.2,
      timeEnd: 44.3,
    },
    {
      id: 15,
      content: "My sister and I go outside.",
      position: 15,
      timeStart: 45,
      timeEnd: 47.29,
    },
    {
      id: 16,
      content: "We begin to make a snowman.",
      position: 16,
      timeStart: 48.1,
      timeEnd: 50.19,
    },
    {
      id: 17,
      content: "My mom starts to shovel the snow.",
      position: 17,
      timeStart: 50.9,
      timeEnd: 53.31,
    },
    {
      id: 18,
      content: "My sister and I make snow angels.",
      position: 18,
      timeStart: 54,
      timeEnd: 56.59,
    },
    {
      id: 19,
      content: "My sister and I throw snowballs.",
      position: 19,
      timeStart: 57.1,
      timeEnd: 59.7,
    },
    {
      id: 20,
      content: "It starts to snow again.",
      position: 20,
      timeStart: 60.2,
      timeEnd: 62,
    },
    {
      id: 21,
      content: "We go inside for hot chocolate.",
      position: 21,
      timeStart: 62.6,
      timeEnd: 65.19,
    },
  ];